# 03 numpy.array 基础

### numpy框架下和矩阵相关的操作

In [2]:
import numpy

### numpy相应的版本号

In [3]:
numpy.__version__

'1.14.3'

### 相当于给numpy取了别名

In [2]:
import numpy as np

In [5]:
np.__version__

'1.14.3'

## Python List的特点

In [6]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
L[5]

5

In [8]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

 List对类型不做限定，其中每一个元素的List还可以是不一样的，这样的结构使得Python的List比较灵活，但也使得它的效率是比较低的，因为对于每一个元素，它需要检查它是具体哪种类型。

In [10]:
L[5] = "Machine Learning"

In [11]:
L

[0, 1, 2, 3, 4, 'Machine Learning', 6, 7, 8, 9]

Python中也有限定只能存储一种类型的数组——array。
缺点：只是将其中的数据当作一个数组来看，或者当作一个二维的数组来看，无论是基于数组也好，二维数组也好，它没有将这些数据看作是向量或矩阵，相应也没有为这些数据配备和向量或矩阵相关的运算，使得在机器学习使用array也不方便，所以numpy框架应运而生。

In [12]:
import array

In [13]:
arr = array.array('i',[i for i in range(10)]) # i代表整型

In [14]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[5] = "Machine Learning"

TypeError: an integer is required (got type str)

### numpy.array
基本操作方式和python的list和array是一样的。

In [17]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
nparr[5]

5

In [20]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [21]:
nparr.dtype

dtype('int32')

In [24]:
nparr[5] = 5.0
nparr[3] = 3.14
nparr # 进行了隐式的类型转换

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
nparr2 = np.array([1,2,3.0])

In [26]:
nparr2.dtype

dtype('float64')

## 其他创建 numpy.array 的方法

不指定dtype，默认类型float64，因为在机器学习的时候，要处理的大多数数据都是浮点型的。但在调用full方法的时候，如果不给填充数据加上小数点，默认的为整型。

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.zeros(10).dtype

dtype('float64')

In [5]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

当我们显式地给出参数名的时候，参数的顺序是可以改变的，而在写代码的时候加不加变量名是看个人习惯的。

In [7]:
np.zeros(shape=(3,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [9]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.full((3,5), fill_value=666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [16]:
np.full(fill_value=666, shape=(3,5))

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

### arange

In [17]:
[i for i in range(0, 20, 2)] # range(起始点, 终止点（不包含该点）, 2（步长，不填默认为1）)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [18]:
np.arange(0, 20, 2) # 和python不同的是在python中不能传入浮点数

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
[i for i in range(0, 20, 0.2)]

TypeError: 'float' object cannot be interpreted as an integer

In [21]:
np.arange(0, 1, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [22]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### linspace

In [24]:
np.linspace(0, 20, 10) # np.linspace(起始点, 终止点, 在 0-20 间等长地截出10个点（包括 0和20 ）)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [25]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### random

In [26]:
np.random.randint(0, 10)

4

In [28]:
np.random.randint(0, 10, 10) # 生成随机数组 np.random.randint(左闭, 右开, 元素个数)

array([3, 9, 6, 3, 1, 7, 1, 8, 9, 4])

In [29]:
np.random.randint(0, 1, 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
np.random.randint(4, 8, size=10)

array([6, 7, 7, 6, 7, 5, 4, 5, 4, 5])

In [31]:
np.random.randint(4, 8, size=(3,5))

array([[4, 7, 4, 7, 4],
       [7, 6, 4, 7, 7],
       [4, 5, 6, 6, 6]])

在计算机中，所有随机数都是伪随机数，都是靠随机数生成算法来完成的，推动算法来生成随机数都会有一个随机数的种子，随机种子可以显式地指明。

In [32]:
np.random.randint(4, 8, size=(3,5)) # 生成随机数不同

array([[6, 5, 5, 5, 6],
       [5, 4, 6, 5, 7],
       [7, 5, 5, 6, 5]])

In [33]:
np.random.seed(666)

In [34]:
np.random.randint(4, 8, size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [35]:
np.random.seed(666)
np.random.randint(4, 8, size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [36]:
np.random.random() # 随机生成浮点数，0-1之间均匀分布

0.2811684913927954

In [37]:
np.random.random(10)

array([0.46284169, 0.23340091, 0.76706421, 0.81995656, 0.39747625,
       0.31644109, 0.15551206, 0.73460987, 0.73159555, 0.8578588 ])

In [38]:
np.random.normal() # 正态分布，均值为0，方差为1

0.7833709215884975

In [40]:
np.random.normal(10, 100) # 均值=10，方差=100

71.36098151346036

In [41]:
np.random.normal(0, 1, (3, 5)) # 均值=0，方差=1，数组大小为3行5列

array([[-0.21747638,  0.22196962, -1.86735182, -0.25584759, -1.76438083],
       [-0.94249688, -1.58045861,  0.90472662, -0.82628327,  0.82101369],
       [ 0.36712592,  1.65399586,  0.13946473, -1.21715355, -0.99494737]])

查询参数  np.random.normal? <br>
查询模块  np.random? <br>
在notebook里进行查看  help(np.random.normal)

In [43]:
np.random.normal? # normal(loc=0.0, scale=1.0, size=None)

In [44]:
np.random?

In [45]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap