# 05 Numpy.array 的基本操作

In [1]:
import numpy as np

In [4]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
X = np.arange(15).reshape(3, 5) # 将一维数组转化为二维数组
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 基本属性

In [6]:
x.ndim # 查询数组的维度

1

In [7]:
X.ndim

2

In [8]:
x.shape # 返回一个元祖，一个元祖里只有一个元素，说明这是一个一维数组，里面有10个元素

(10,)

In [9]:
X.shape # 两个维度，三行五列

(3, 5)

In [10]:
x.size # 元素个数

10

In [11]:
X.size

15

### numpy.array 的数据访问

In [12]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x[0]

0

In [14]:
x[-1]

9

In [15]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
X[0][0] # 这样写访问一个元素是没问题的，但在numpy中不建议这样写

0

In [20]:
X[(2, 2)]

12

切片语法

In [21]:
x[0:5]

array([0, 1, 2, 3, 4])

In [22]:
x[:5]

array([0, 1, 2, 3, 4])

In [23]:
x[5:]

array([5, 6, 7, 8, 9])

In [24]:
x[::2] # 2 代表步长

array([0, 2, 4, 6, 8])

In [25]:
x[::-1] # 步长取负数代表倒数的访问

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [27]:
X[:2, :3] # 前两行，前三列

array([[0, 1, 2],
       [5, 6, 7]])

 取前两行之后，再取一次3本意是取前三列，但是python解析的时候会解析成这个数组中的前三个元组，但是现在这个数组中只有两个元组，所以我们只能取到前两个元组，最终得到的依然是前两个元组。所以 X[:2][:3] 这样索引不能表达我们的语义。

In [28]:
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
X[:2] # 取前两行

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
X[:3][:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
X[:2, ::2] # 访问前两行，但是对于每一行，都访问从头到尾但是间隔为2的元素

array([[0, 2, 4],
       [5, 7, 9]])

In [32]:
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [33]:
X[0]

array([0, 1, 2, 3, 4])

In [34]:
X[0, :] # 此时它是一个向量

array([0, 1, 2, 3, 4])

In [35]:
X[0, :].ndim

1

In [36]:
X[:, 0] # 取第一列

array([ 0,  5, 10])

In [37]:
X[:, 0].ndim

1

In [39]:
subX = X[:2, :3] # 前两行，前三列
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [41]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

那么原矩阵中元素是否发生改变呢？如果实在python的list中，使用这种切片其实是创建了一个全新的矩阵，换句话说 subX 和原来的 X 没有任何的关系，但是在numpy中不是这样的。X 的第 0 行第 0 列也变成了100。

In [42]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

这是因为对numpy来说，优先考虑的是效率，所以对于这种取子矩阵的方式，numpy是快速地利用引用的方式获得的这个子矩阵，此时修改子矩阵中的元素会影响原矩阵，同理，如果我们修改原矩阵中的元素，子矩阵中元素也会发生相应改变。

In [44]:
X[0, 0] = 0
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [45]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

创建一个和原矩阵不相干的子矩阵。

In [46]:
subX = X[:2, :3].copy()
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [50]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [52]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### Reshape

In [53]:
x.shape

(10,)

In [54]:
x.ndim

1

In [55]:
x.reshape(2, 5) # 但该改变并没有改变x自身

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [56]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
A = x.reshape(2, 5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

一维的向量和二维的数组或矩阵是两个概念。
一维的向量它只有一个维度，这个维度有10个元素。

In [61]:
B = x.reshape(1, 10) # 使B为1*10的二维矩阵，它有两个方括号[]
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [62]:
B.ndim

2

In [63]:
B.shape

(1, 10)

In [64]:
x.reshape(10, -1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [65]:
x.reshape(-1, 10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [66]:
x.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [67]:
x.reshape(3, -1) # 10不能被3整除

ValueError: cannot reshape array of size 10 into shape (3,newaxis)

### 合并操作

In [73]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [69]:
x

array([1, 2, 3])

In [70]:
y

array([3, 2, 1])

In [71]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [74]:
z = np.array([666, 666, 666])

In [75]:
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [76]:
A = np.array([[1, 2, 3],
             [4, 5, 6]])

In [77]:
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [78]:
np.concatenate([A, A], axis=1) # axis 轴，默认为0，也就是沿着第一个维度（行）的方向进行拼接，就是原来有两行，现在有四行
# 当axis=1，也就是沿着第二个维度（列）的方向进行拼接，这样我们就获得2*6的矩阵

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [81]:
np.concatenate([A, z]) # 维数不一样，无法进行拼接

ValueError: all the input arrays must have same number of dimensions

In [80]:
np.concatenate([A, z.reshape(1, -1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [82]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
A2 = np.concatenate([A, z.reshape(1, -1)])

In [84]:
A2

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [85]:
np.vstack([A, z]) # 垂直方向将数据叠在一起，容错性更好，对于列表传入的两个数组可以非常智能地判断出来怎样在垂直的方向进行叠加，即使维度不同

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [87]:
B = np.full((2, 2), 100)
B

array([[100, 100],
       [100, 100]])

In [88]:
np.hstack([A, B]) # 水平方向堆叠在一起

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [89]:
np.hstack([A, z]) # 非法数据报错

ValueError: all the input arrays must have same number of dimensions

### 分割操作

In [90]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
x1, x2, x3 = np.split(x, [3, 7]) # np.split(数组, [分割点])

In [93]:
x1

array([0, 1, 2])

In [94]:
x2

array([3, 4, 5, 6])

In [95]:
x3

array([7, 8, 9])

In [96]:
x1, x2 = np.split(x, [5])

In [97]:
x1

array([0, 1, 2, 3, 4])

In [98]:
x2

array([5, 6, 7, 8, 9])

In [100]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [101]:
A1, A2 = np.split(A, [2]) # 默认基于行所在维度分割

In [102]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [103]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [105]:
A1, A2 = np.split(A, [2], axis=1)

In [106]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [107]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [108]:
upper, lower = np.vsplit(A, [2])

In [109]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [110]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [111]:
left, right = np.hsplit(A, [2])

In [112]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [113]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [114]:
data = np.arange(16).reshape((4, 4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [116]:
x, y = np.hsplit(data, [-1])

In [117]:
x

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [118]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [119]:
y[:, 0] # 将y转化为一个向量

array([ 3,  7, 11, 15])