# 聚合操作

将一组值变为一个值。

In [1]:
import numpy as np

L = np.random.random(100)

In [2]:
L

array([0.90891397, 0.00381748, 0.25237392, 0.35139082, 0.46289688,
       0.74634416, 0.97917756, 0.61781293, 0.59231126, 0.64994454,
       0.86038306, 0.5706765 , 0.5696452 , 0.89845053, 0.76609929,
       0.01547159, 0.01280409, 0.60175801, 0.74290612, 0.89660653,
       0.91091549, 0.34138306, 0.78781198, 0.25601229, 0.97411614,
       0.84555878, 0.09861524, 0.84788491, 0.59705232, 0.60631886,
       0.97978099, 0.03940852, 0.60058665, 0.48373858, 0.68721389,
       0.10962508, 0.11769003, 0.60192161, 0.53807895, 0.70655478,
       0.32852779, 0.14079325, 0.64654732, 0.50070821, 0.01723228,
       0.77088123, 0.69417437, 0.8779775 , 0.09379434, 0.08001289,
       0.61429601, 0.14721571, 0.98360582, 0.73826736, 0.04055593,
       0.47771016, 0.5101238 , 0.64726435, 0.5687455 , 0.76760011,
       0.47601863, 0.98167655, 0.71115504, 0.10011998, 0.16998569,
       0.28051359, 0.12311911, 0.02935249, 0.68987874, 0.82109108,
       0.05470016, 0.67889835, 0.07629769, 0.50951725, 0.27605

In [3]:
sum(L)

51.915152876749396

In [4]:
np.sum(L)

51.91515287674938

原生的sum()的效率远远低于num.sum()的效率。

In [5]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

129 ms ± 626 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
854 µs ± 20.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


调用聚合函数的两种方式，更推荐使用第一种方式，因为个别的运算符numpy的实现中没有定义在这个向量中，np.这种方法相对来说是更全的，而且使用这种方式可以显示地告诉阅读者我在使用numpy这个库中的方法进行运算。 <br>
第一种方式：

In [6]:
np.min(big_array)

8.174128658389179e-07

In [7]:
np.max(big_array)

0.9999997593356554

第二种方式：

In [8]:
big_array.min()

8.174128658389179e-07

In [9]:
big_array.max()

0.9999997593356554

In [10]:
big_array.sum()

500146.86379574303

In [11]:
X = np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

二维数组

In [12]:
np.sum(X)

120

In [13]:
np.sum(X, axis=0) # 默认值为0，沿着列进行计算，逐列相加

array([24, 28, 32, 36])

In [14]:
np.sum(X, axis=1) # 沿着行进行计算，逐行相加

array([ 6, 22, 38, 54])

In [15]:
np.prod(X) # 所有元素相乘

0

In [17]:
np.prod((X + 1).astype('int64'))

20922789888000

均值、中位数、百分位、方差和标准差 <br>
当样本中有一个值很大时，平均值不能很好地描述样本。

In [18]:
np.mean(X) # 求平均值

7.5

In [19]:
np.median(X) # 求中位数

7.5

In [20]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2

In [21]:
np.median(v)

2.0

In [22]:
np.percentile(big_array, q=50) # np.percentile(数组, q=百分位)  在big_array中50%的数都小于0.5004775694316687

0.5004775694316687

In [24]:
np.percentile(big_array, q=100)

0.9999997593356554

In [25]:
np.max(big_array)

0.9999997593356554

In [26]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=percent))

8.174128658389179e-07
0.25023155046824397
0.5004775694316687
0.7499303214733737
0.9999997593356554


In [27]:
np.var(big_array) # 求方差

0.08327608990009105

In [28]:
np.std(big_array) # 求标准差

0.2885759690273794

In [30]:
x = np.random.normal(0, 1, size=1000000) # 取正态分布随机数

In [31]:
np.mean(x)

-0.00023333245101731518

In [32]:
np.std(x)

0.9997774506715551

### 索引

In [33]:
np.min(x)

-4.841634756961509

In [34]:
np.argmin(x) # 最小值的索引

982061

In [35]:
x[982061]

-4.841634756961509

In [38]:
np.max(x)

4.769956090284952

In [36]:
np.argmax(x) # 最大值的索引

3833

In [37]:
x[3833]

4.769956090284952

### 排序和使用索引

一维数组

In [40]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [42]:
np.random.shuffle(x) # 对向量进行乱序处理
x

array([ 2, 13,  9, 11,  8,  6, 10,  1, 14, 15, 12,  0,  4,  5,  7,  3])

In [43]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [44]:
x

array([ 2, 13,  9, 11,  8,  6, 10,  1, 14, 15, 12,  0,  4,  5,  7,  3])

In [45]:
x.sort()

In [46]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

二维数组

In [47]:
X = np.random.randint(10, size=(4,4))
X

array([[8, 3, 7, 0],
       [1, 9, 0, 8],
       [2, 7, 8, 4],
       [4, 2, 1, 3]])

In [48]:
np.sort(X) # 把每一行按照顺序进行排序

array([[0, 3, 7, 8],
       [0, 1, 8, 9],
       [2, 4, 7, 8],
       [1, 2, 3, 4]])

In [49]:
np.sort(X, axis=1) # 默认值是1,逐行排序

array([[0, 3, 7, 8],
       [0, 1, 8, 9],
       [2, 4, 7, 8],
       [1, 2, 3, 4]])

In [50]:
np.sort(X, axis=0) # 逐列排序

array([[1, 2, 0, 0],
       [2, 3, 1, 3],
       [4, 7, 7, 4],
       [8, 9, 8, 8]])

一维数组

In [51]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [52]:
np.random.shuffle(x)

In [53]:
x

array([13,  0,  6, 12,  4,  3, 11, 15, 10,  7,  9,  5, 14,  8,  1,  2])

In [54]:
np.argsort(x)

array([ 1, 14, 15,  5,  4, 11,  2,  9, 13, 10,  8,  6,  3,  0, 12,  7],
      dtype=int64)

In [55]:
np.partition(x, 3) # np.partition(向量, 标定点) 执行后把小于标定点的元素放在标定点左边，大于标定点的元素放在标定点右边，注意：向量不一定是有序的

array([ 1,  2,  0,  3,  4,  5,  6,  7,  8, 10,  9, 12, 11, 13, 14, 15])

In [56]:
np.argpartition(x, 3) # 返回索引

array([14, 15,  1,  5,  4, 11,  2,  9, 13,  8, 10,  3,  6,  0, 12,  7],
      dtype=int64)

二维数组

In [57]:
X

array([[8, 3, 7, 0],
       [1, 9, 0, 8],
       [2, 7, 8, 4],
       [4, 2, 1, 3]])

In [58]:
np.argsort(X, axis=1)

array([[3, 1, 2, 0],
       [2, 0, 3, 1],
       [0, 3, 1, 2],
       [2, 1, 3, 0]], dtype=int64)

In [59]:
np.argsort(X, axis=0)

array([[1, 3, 1, 0],
       [2, 0, 3, 3],
       [3, 2, 0, 2],
       [0, 1, 2, 1]], dtype=int64)

In [60]:
np.argpartition(X, 2, axis=1)

array([[3, 1, 2, 0],
       [2, 0, 3, 1],
       [0, 3, 1, 2],
       [2, 1, 3, 0]], dtype=int64)