In [47]:
import numpy as np
import matplotlib.pyplot as plt

raw_data_X = [[3.393533211, 2.331273381],
              [3.110073483, 1.781539638],
              [1.343808831, 3.368360954],
              [3.582294042, 4.679179110],
              [2.280362439, 2.866990263],
              [7.423436942, 4.696522875],
              [5.745051997, 3.533989803],
              [9.172168622, 2.511101045],
              [7.792783481, 3.424088941],
              [7.939820817, 0.791637231]
             ]
raw_data_y = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]

X_train = np.array(raw_data_X)
y_train = np.array(raw_data_y)

x = np.array([8.093607318, 3.365731514])

In [48]:
%run kNN_function/kNN.py

In [49]:
predict_y = kNN_classify(6, X_train, y_train,x)

In [50]:
predict_y

1

### 使用scikit-learn中的kNN

In [51]:
from sklearn.neighbors import KNeighborsClassifier

In [52]:
kNN_classifier = KNeighborsClassifier(n_neighbors=6)

In [53]:
kNN_classifier.fit(X_train, y_train) # 返回机器学习对象自身

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=6, p=2,
           weights='uniform')

In [54]:
kNN_classifier.predict(x) # 希望传入一个矩阵而不是一维数组

ValueError: Expected 2D array, got 1D array instead:
array=[8.09360732 3.36573151].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [55]:
X_predict = x.reshape(1, -1)

In [56]:
X_predict

array([[8.09360732, 3.36573151]])

In [57]:
kNN_classifier.predict(X_predict)

array([1])

In [58]:
y_predict = kNN_classifier.predict(X_predict)

In [59]:
y_predict[0]

1

### 重新整理我们的kNN的代码

In [60]:
%run KNN/kNN.py

In [61]:
knn_clf = KNNClassifier(k=6) # 分类器

In [62]:
knn_clf.fit(X_train, y_train)

KNN(k=6)

In [63]:
y_predict = knn_clf.predict(X_predict)

In [64]:
y_predict

array([1])

In [65]:
y_predict[0]

1