# 测试我们的算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data
y = iris.target

In [4]:
X.shape

(150, 4)

In [5]:
y.shape

(150,)

### train_test_split

In [6]:
y # 不能直接去前k歌作为训练数据集，因为该数据集是排好序的

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
shuffle_indexes = np.random.permutation(len(X)) # 随机排列索引

In [13]:
shuffle_indexes

array([ 35,  39,  75,  94,  56, 140,   8, 124,  31,  36, 149,  19,  60,
       105,  38,   5,  99,  84, 130,  52,   4,  20, 123, 108, 103, 125,
       142,  46,  32,  82,  73,   6,  59,  13,  17,  85,  58,  80,  24,
        16, 110,  33, 107,  40, 112,  21, 133,  15,  89,  65,  96,  98,
        62,  68, 135,  12, 148, 101,  44, 146, 144, 109,  67,  25, 147,
        26,  79, 104, 141,  97, 113, 118,  76, 132, 119,   9,  51,  49,
        95, 100,  48,  86,  10,  88,  55,  47,  77, 134,  50,  54,  43,
        45,   2,  71,  11,  64,  28,  66,  93, 102, 143, 106,   0, 120,
         7,  69,  34,  83,   1, 131,  74,  57,  90, 111, 137, 116, 129,
        91, 136, 115,  81, 128,  41,  53,   3, 127,  27,  72, 121, 139,
       138, 114, 145,  92,  23,  87,  61,  78,  42, 117, 126,  30,  22,
        37,  29,  70,  14, 122,  63,  18])

In [14]:
test_ratio = 0.2 # 测试数据集比例
test_size = int(len(X) * test_ratio)

In [15]:
test_size

30

In [16]:
test_indexes = shuffle_indexes[:test_size] # 前20%是测试数据集
train_indexes = shuffle_indexes[test_size:] # 后80%是训练数据集

In [17]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [18]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [20]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


### 使用我们的算法

In [22]:
from kNN.model_selection import train_test_split

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [24]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [25]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [26]:
from kNN.kNN import KNNClassifier

In [27]:
my_knn_clf = KNNClassifier(k=3)

In [28]:
my_knn_clf.fit(X_train, y_train)

KNN(k=3)

In [29]:
y_predict = my_knn_clf.predict(X_test)

In [30]:
y_predict

array([1, 0, 1, 2, 2, 1, 0, 0, 0, 1, 2, 1, 2, 2, 0, 0, 0, 1, 2, 1, 1, 2,
       0, 2, 2, 1, 1, 1, 2, 2])

In [31]:
y_test

array([1, 0, 1, 2, 2, 1, 0, 0, 0, 1, 2, 1, 1, 2, 0, 0, 0, 1, 2, 1, 1, 2,
       0, 2, 2, 1, 1, 1, 2, 2])

In [32]:
sum(y_predict == y_test)

29

In [33]:
sum(y_predict == y_test)/len(y_test)

0.9666666666666667

### sklearn中的train_test_split

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666) # random_state 随机数种子

In [37]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [38]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [39]:
from sklearn.neighbors import KNeighborsClassifier

In [40]:
my_knn_clf = KNNClassifier(k=3)

In [41]:
my_knn_clf.fit(X_train, y_train)

KNN(k=3)

In [42]:
y_predict = my_knn_clf.predict(X_test)

In [43]:
y_predict

array([1, 0, 2, 0, 2, 0, 0, 0, 2, 0, 2, 1, 0, 2, 2, 2, 2, 0, 2, 1, 2, 2,
       0, 2, 1, 0, 0, 1, 1, 0])

In [45]:
sum(y_predict == y_test)

28